id: P000307
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:10.563542
source_metadata:
  id: bdr:W22323
  title: ཡིག་དྲུག་གི་འཁོར་ལོའི་ཁུངས་དང་བསྐོར་ཚུལ་གྱི་གནད་དམིགས་པ་བྱ་ཚུལ་ཕན་ཡོན་དང་བཅས་པ
  author: ''
  volumes:
    6fd9ad339ca2417091c75b7f6a351e03:
      image_group_id: I1PD36249
      title: Volume 1 of bcom ldan 'das dpal rnam par snang mdzad kyi bum chog
      volume_number: 1
      total_pages: 42
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
